=== ShenJiaFa/Java-Guide/src/com/shenjiafa/theory/xml/constraint/bookshelf_schema/bookshelf.xsd
<?xml version="1.0" encoding="utf-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="shenjiafa"
        elementFormDefault="qualified">
    <element name="bookshelf">
        <complexType>
            <sequence maxOccurs="unbounded">
                <element name="book">
                    <complexType>
                        <sequence>
                            <element name="bookName" type="string"/>
                            <element name="author" type="string"/>
                            <element name="price" type="double"/>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== ShenJiaFa/Java-Guide/src/com/shenjiafa/theory/xml/constraint/bookshelf_schema/bookshelf_schema.xml
<?xml version="1.0" encoding="utf-8" ?>
<bookshelf xmlns="shenjiafa"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="shenjiafa  bookshelf.xsd">
    <book>
        <bookName>Java Guide 1.0</bookName>
        <author>James</author>
        <price>18.8</price>
    </book>
    <book>
        <bookName>Java Guide 2.0</bookName>
        <author>Jack</author>
        <price>20.8</price>
    </book>
    <book>
        <bookName>Java Guide 3.0</bookName>
        <author>Jim</author>
        <price>22.8</price>
    </book>
</bookshelf>
